on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Website Password'
        required: true
        type: string

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4

      - name: Install staticrypt
        run: npm install -g staticrypt

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          packages: |
            any::staticryptR

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Mask input password and add to GitHub environment
        run: |
          STATICRYPT_PASSWORD=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.password' )
          echo "::add-mask::$STATICRYPT_PASSWORD"
          echo STATICRYPT_PASSWORD=$STATICRYPT_PASSWORD >> $GITHUB_ENV

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
